### ISSUE TITLE
Use PyPI release rather than github archive?

### ISSUE THREAD

**Issue by Huite** [conda-forge/timml-feedstock#12]
### Comment:

Hi @jentjr,

Mark released a new version, both on pypi and in the github archives for TimML and TTim. I setup a conda recipe for [ttim](https://github.com/conda-forge/ttim-feedstock) and got an update. To my surprise, it looks like the bot didn't create a PR here. I think this is because Mark made a typo with an earlier release, writing 6.04 rather than 6.0.4.

I'd guess the bot parses 6.04 as 6.4, which is higher than the latest release 6.1.0. The PyPI releases are fine though.

Is there any reason you chose the github archive in the meta.yml rather than the [PyPI page](https://pypi.org/project/timml/)?

(This creates a minor issue for me now, because we're organizing a course on Thursday ... 😅 )

**Comment by Huite** [comment]
Another question: I don't think Mark uses conda-forge that much, might be sensible to add each other the recipe maintainer lists?

**Comment by jentjr** [comment]
Okay, that's good.
