### ISSUE TITLE
Drop `libgfortran`

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/timml-feedstock#2]
Appears the recipe is [explicitly listing `libgfortran` in `host`]( https://github.com/conda-forge/timml-feedstock/blob/a43825233417dab2c1898e6c1be4df66cf72ba64/recipe/meta.yaml#L26 ) and [`run`]( https://github.com/conda-forge/timml-feedstock/blob/a43825233417dab2c1898e6c1be4df66cf72ba64/recipe/meta.yaml#L36 ). However this is not needed as the `fortran` compilers list [`libgfortran` in `run_exports`]( https://github.com/conda-forge/toolchain-feedstock/blob/ca83bdace0009769bea574a9fdbde44183ecb825/recipe/meta.yaml#L44-L46 ) for [both of them]( https://github.com/AnacondaRecipes/aggregate/blob/72bfe3466a669c22fbf7316e076377395cdc61f8/gfortran-feedstock/recipe/meta.yaml#L60-L62 ). So they will automatically be added at run time for any package using them. Not to mention the compilers require these libraries themselves. As a result, `libgfortran` can and should be dropped from the recipe.

**Comment by jentjr** [comment]
I had to add libgfortran to get the GCC 7 builds to work. When I remove libgfortran all the builds except linux with python 3.6 and gfortran pass. Any ideas why?

Thanks!

**Comment by jakirkham** [comment]
Not sure. There are a lot of moving parts for the compiler migration.

In any event, the PR looked fine. The failure wasn't related to `libgfortran`, but was caused by the upload failing. The build itself passed.
